---
language: python
python: "2.7"

env:
  - SITE=test-install-package.yml

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  - ansible-galaxy install geerlingguy.git --force

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - >
    git lfs version | awk -F' ' '{print $1}' | awk -F'/' '{print $2}'
    | grep -q '1.4.4'
    && (echo 'version test: pass' && exit 0)
    || (echo 'version test: fail' && exit 1)

  # Make sure git is installed and at the correct version.
  - which git-lfs
  - git lfs env

after_failure:
  # If we failed, it's likely due to Travis environment changes.
  - which git
  - git --version
